# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCheckcsv():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_checkcsv(self):
    self.driver.get("http://localhost:5000/")
    self.driver.set_window_size(1854, 923)
    self.driver.find_element(By.LINK_TEXT, "Spurs Ring Winners").click()
    self.driver.find_element(By.ID, "btnGroupDrop175").click()
    self.driver.find_element(By.LINK_TEXT, "Syntax check").click()
    WebDriverWait(self.driver, 10).until(
      expected_conditions.visibility_of_element_located((By.ID, "check_175"))
    )
    badge = self.driver.find_element(By.CSS_SELECTOR, "#check_175 .badge.bg-success").text
    assert badge.strip() == "Valid Model"
    self.driver.find_element(By.ID, "btnGroupDrop176").click()
    self.driver.find_element(By.LINK_TEXT, "Syntax check").click()
    WebDriverWait(self.driver, 10).until(
      expected_conditions.visibility_of_element_located((By.ID, "check_175"))
    )
    badge = self.driver.find_element(By.CSS_SELECTOR, "#check_175 .badge.bg-success").text
    assert badge.strip() == "Valid Model"
    self.driver.find_element(By.ID, "btnGroupDrop177").click()
    self.driver.find_element(By.LINK_TEXT, "Syntax check").click()
    WebDriverWait(self.driver, 10).until(
      expected_conditions.visibility_of_element_located((By.ID, "check_175"))
    )
    badge = self.driver.find_element(By.CSS_SELECTOR, "#check_175 .badge.bg-success").text
    assert badge.strip() == "Valid Model"
    self.driver.find_element(By.ID, "btnGroupDrop178").click()
    self.driver.find_element(By.LINK_TEXT, "Syntax check").click()
    WebDriverWait(self.driver, 10).until(
      expected_conditions.visibility_of_element_located((By.ID, "check_175"))
    )
    badge = self.driver.find_element(By.CSS_SELECTOR, "#check_175 .badge.bg-success").text
    assert badge.strip() == "Valid Model"
    self.driver.find_element(By.ID, "btnGroupDrop179").click()
    self.driver.find_element(By.LINK_TEXT, "Syntax check").click()
    WebDriverWait(self.driver, 10).until(
      expected_conditions.visibility_of_element_located((By.ID, "check_175"))
    )
    badge = self.driver.find_element(By.CSS_SELECTOR, "#check_175 .badge.bg-success").text
    assert badge.strip() == "Valid Model"
  