# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestReplycomment():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_replycomment(self):
    self.driver.get("http://localhost/")
    self.driver.set_window_size(706, 923)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Pau Gasol Teams").click()
    self.driver.find_element(By.LINK_TEXT, "View all comments").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-sm").click()
    self.driver.find_element(By.ID, "commentContent").click()
    self.driver.find_element(By.ID, "commentContent").send_keys("U r right!!")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link > .text-dark").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
  
