# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestReplycomment():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_replycomment(self):
    self.driver.get("http://localhost/")
    self.driver.set_window_size(706, 923)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Pau Gasol Teams").click()
    self.driver.find_element(By.LINK_TEXT, "View all comments").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-sm").click()
    self.driver.find_element(By.ID, "commentContent").click()
    self.driver.find_element(By.ID, "commentContent").send_keys("U r right!!")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link > .text-dark").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
  
class TestLikedislikecomments():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_likedislikecomments(self):
    self.driver.get("http://localhost/")
    self.driver.set_window_size(706, 923)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("user4@example.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(5) > .col-lg-6").click()
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Michael Jordan Teams").click()
    self.driver.find_element(By.LINK_TEXT, "View all comments").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-inline:nth-child(1) path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-inline:nth-child(2) path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-secondary path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link > .text-dark").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
    
class TestCommentdataset():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_commentdataset(self):
    self.driver.get("http://localhost/")
    self.driver.set_window_size(706, 923)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("user3@example.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Spurs Ring Winners").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex > .btn:nth-child(1)").click()
    self.driver.find_element(By.ID, "commentContent").click()
    self.driver.find_element(By.ID, "commentContent").send_keys("I like!")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".justify-content-between > .btn").click()
    self.driver.find_element(By.ID, "commentContent").click()
    self.driver.find_element(By.ID, "commentContent").send_keys("Thanks for sharing!!!")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Gasol, Pau").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()
    
class TestAuthorpincomment():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_authorpincomment(self):
    self.driver.get("http://localhost/")
    self.driver.set_window_size(706, 923)
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("user2@example.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.LINK_TEXT, "Season 2023-24").click()
    self.driver.find_element(By.LINK_TEXT, "View all comments").click()
    self.driver.find_element(By.CSS_SELECTOR, ".comment-card:nth-child(1) .d-flex > .d-flex > .d-inline:nth-child(1) svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".comment-card:nth-child(1) .d-flex > .d-flex > .d-inline:nth-child(1) svg").click()
    self.driver.find_element(By.LINK_TEXT, "Doncic, Luka").click()
    self.driver.find_element(By.LINK_TEXT, "Log out").click()