# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set this environment variable to suppress the "Running as root" warning from pip
ENV PIP_ROOT_USER_ACTION=ignore

# Install necessary packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends mariadb-client \
    && apt-get install -y --no-install-recommends gcc libc-dev python3-dev libffi-dev \
    && apt-get install -y --no-install-recommends curl \
    && apt-get install -y --no-install-recommends bash \
    && apt-get install -y --no-install-recommends openrc \
    && apt-get install -y --no-install-recommends build-essential 

# Install Docker CLI
RUN apt-get install -y --no-install-recommends ca-certificates gnupg lsb-release \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends docker-ce-cli 

# --- NUEVO: INSTALACIÓN DE FIREFOX Y GECKODRIVER PARA SELENIUM ---
# 1. Instalar Firefox ESR y dependencias del sistema (GTK, X11, Audio, etc.)
RUN apt-get install -y --no-install-recommends \
    firefox-esr \
    wget \
    tar \
    bzip2 \
    libxtst6 \
    libgtk-3-0 \
    libdbus-glib-1-2 \
    libx11-xcb1 \
    libdbus-1-3 \
    libasound2

# 2. Instalar Geckodriver (Driver para controlar Firefox)
RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz \
    && tar -xvzf geckodriver-v0.34.0-linux64.tar.gz \
    && chmod +x geckodriver \
    && mv geckodriver /usr/local/bin/ \
    && rm geckodriver-v0.34.0-linux64.tar.gz
# --- FIN DEL BLOQUE NUEVO ---

# Clean up (Limpiamos caché después de instalar todo)
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/*
        
# Set the working directory in the container to /app
WORKDIR /app

# Copy requirements.txt to the /app working directory
COPY requirements.txt .

# Removes cache at the build stage
RUN find . -type d -name "__pycache__" -exec rm -r {} + && \
    find . -type f -name "*.pyc" -exec rm -f {} +

# Copy the wait-for-db.sh script and set execution permissions
COPY --chmod=0755 scripts/wait-for-db.sh ./scripts/

# Copy the init-testing-db.sh script and set execution permissions
COPY --chmod=0755 scripts/init-testing-db.sh ./scripts/

# Copy files
COPY rosemary/ ./rosemary
COPY pyproject.toml ./
COPY docker/ ./docker

# Update pip
RUN pip install --no-cache-dir --upgrade pip

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Install Rosemary
RUN pip install -e ./

# Expose port 5000 for the Flask app
EXPOSE 5000