"""empty message

Revision ID: 004
Revises: 003
Create Date: 2025-12-14 15:44:27.297201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comment_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'comment', ['parent_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ds_meta_data', schema=None) as batch_op:
        batch_op.alter_column('extra_fields',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_meta_data', schema=None) as batch_op:
        batch_op.alter_column('extra_fields',
               existing_type=sa.String(length=120),
               type_=mysql.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comment_ibfk_2'), 'comment', ['parent_id'], ['id'])

    # ### end Alembic commands ###
